#!/bin/bash

program=tsgettoolbox

pkgs="\
     setuptools \
     nose \
     dateutil \
     pandas \
     pip \
     coverage \
     flake8 \
     odo \
     "

# 2.6 is not available for networkx requirement
envs=(2.7 3.3 3.4 3.5)

for env in ${envs[@]}; do
    echo "${env}"

    pew in python${env} << EOT

    pip install --upgrade ${pkgs}
    pip install --no-deps --upgrade ../mando/
    pip uninstall -y ${program}
    rm -rf build
    pip install --upgrade --no-deps ../${program}/

    nosetests \
        --with-doctest \
        --with-coverage \
        --cover-tests \
        --cover-package=${program} \
        --cover-branches \
        --cover-erase
    exit
EOT
done


pew in python3.4 << EOTT
coverage erase
coverage run `which nosetests` --with-doctest
coverage report --include="tsgettoolbox/*" --omit="tests/*"
coverage html --include="tsgettoolbox/*" --omit="tests/*"
flake8 tsgettoolbox/__init__.py tsgettoolbox/services/__init__.py --exit-zero

cd docsrc
make clean
make html
exit
EOTT
