#!/bin/bash

program=tsgettoolbox

pkgs="\
     setuptools \
     pip \
     pytest \
     coverage \
     flake8 \
     "

envs=(~/python_ves/python-2.7.13
      ~/python_ves/python-3.5.2 \
      ~/python_ves/python-3.6.0)

pytest_opts='--doctest-modules --ignore docsrc --mpl'

for env in ${envs[@]}; do
    echo "${env}"

    source "${env}"/bin/activate
    pip install --upgrade pip
    pip install wheel
    pip install --upgrade --only-binary pandas,scipy ${pkgs}
    pip install -r etc/requirements_ci.txt
    pip uninstall -y ${program}
    rm -rf build
    python setup.py develop

    pytest ${pytest_opts}
    deactivate
done

source "${env}"/bin/activate
coverage erase
coverage run `which pytest` ${pytest_opts}
coverage report --include="${program}/*" --omit="tests/*"
coverage html --include="${program}/*" --omit="tests/*"
flake8 ${program}/__init__.py ${program}/${program}.py ${program}/tsutils.py ${program}/functions/*.py --exit-zero
deactivate
